# Generated by Django 4.1.7 on 2023-03-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name1', models.CharField(max_length=20)),
                ('art_val1', models.PositiveSmallIntegerField(default=5)),
                ('art_name2', models.CharField(max_length=20)),
                ('art_val2', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.PositiveSmallIntegerField(default=5)),
                ('con', models.PositiveSmallIntegerField(default=5)),
                ('siz', models.PositiveSmallIntegerField(default=5)),
                ('dex', models.PositiveSmallIntegerField(default=5)),
                ('app', models.PositiveSmallIntegerField(default=5)),
                ('int', models.PositiveSmallIntegerField(default=5)),
                ('pow', models.PositiveSmallIntegerField(default=5)),
                ('edu', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting', models.PositiveSmallIntegerField(default=10)),
                ('anthropology', models.PositiveSmallIntegerField(default=1)),
                ('archaeology', models.PositiveSmallIntegerField(default=1)),
                ('astronomy', models.PositiveSmallIntegerField(default=1)),
                ('bargain', models.PositiveSmallIntegerField(default=5)),
                ('biology', models.PositiveSmallIntegerField(default=1)),
                ('chemistry', models.PositiveSmallIntegerField(default=1)),
                ('climb', models.PositiveSmallIntegerField(default=40)),
                ('conceal', models.PositiveSmallIntegerField(default=15)),
                ('craft', models.PositiveSmallIntegerField(default=5)),
                ('credit_rating', models.PositiveSmallIntegerField(default=15)),
                ('cthulhu_mythos', models.PositiveSmallIntegerField(default=0)),
                ('disguise', models.PositiveSmallIntegerField(default=1)),
                ('dodge', models.PositiveSmallIntegerField(default=0)),
                ('drive_auto', models.PositiveSmallIntegerField(default=20)),
                ('electrical_repair', models.PositiveSmallIntegerField(default=10)),
                ('fast_talk', models.PositiveSmallIntegerField(default=5)),
                ('first_aid', models.PositiveSmallIntegerField(default=30)),
                ('geology', models.PositiveSmallIntegerField(default=1)),
                ('arts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investigator.arts')),
            ],
        ),
        migrations.CreateModel(
            name='Investigative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField(default=1)),
                ('sex', models.CharField(default='Man', max_length=6)),
                ('luck', models.PositiveSmallIntegerField(default=1)),
                ('characteristics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investigator.characteristics')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investigator.skills')),
            ],
        ),
    ]
